package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ASKING_ENTITY.
 */
public class AskingEntity extends BaseEntity  {

    private String userId;
    private Integer category;
    private String question;
    private String replies;
    private java.util.Date updatedAt;

    public AskingEntity() {
    }

    public AskingEntity(String objectId) {
        this.objectId = objectId;
    }

    public AskingEntity(String objectId, java.util.Date createdAt, String userId, Integer category, String question, String replies, java.util.Date updatedAt) {
        this.objectId = objectId;
        this.createdAt = createdAt;
        this.userId = userId;
        this.category = category;
        this.question = question;
        this.replies = replies;
        this.updatedAt = updatedAt;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getReplies() {
        return replies;
    }

    public void setReplies(String replies) {
        this.replies = replies;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
