package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT_REQUEST_ENTITY.
 */
public class ContactRequestEntity extends MessageEntity  {

    /** Not-null value. */
    private String userId;
    private String info;

    public ContactRequestEntity() {
    }

    public ContactRequestEntity(String userId) {
        this.userId = userId;
    }

    public ContactRequestEntity(String userId, java.util.Date createdAt, String info, Boolean isRead) {
        this.userId = userId;
        this.createdAt = createdAt;
        this.info = info;
        this.isRead = isRead;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

}
