package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT_REQUEST_ENTITY.
 */
public class ContactRequestEntity {

    private Long id;
    private String context;
    /** Not-null value. */
    private String userId;
    private String intro;

    public ContactRequestEntity() {
    }

    public ContactRequestEntity(Long id) {
        this.id = id;
    }

    public ContactRequestEntity(Long id,
                                String context,
                                String userId,
                                String intro) {
        this.id = id;
        this.context = context;
        this.userId = userId;
        this.intro = intro;
    }

    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

}
