package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOMENT_LIKE_ENTITY.
 */
public class MomentLikeEntity {

    private Long id;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private String momentId;

    public MomentLikeEntity() {
    }

    public MomentLikeEntity(Long id) {
        this.id = id;
    }

    public MomentLikeEntity(Long id, String userId, java.util.Date createdAt, String momentId) {
        this.id = id;
        this.userId = userId;
        this.createdAt = createdAt;
        this.momentId = momentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public String getMomentId() {
        return momentId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMomentId(String momentId) {
        this.momentId = momentId;
    }

}
