package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.util.Date;

/**
 * Entity mapped to table USER_VM.
 */
public class UserEntity extends BaseEntity {

    private String username;
    private String chatId;
    private String screenName;
    private String email;
    private Integer city;
    private Integer area;
    private String avatarUrl;
    private String about;
    private String contacts;
    private String messages;
    private String parties;
    private String askings;
    private String favParties;
    private String favAskings;

    public UserEntity() {
    }

    public UserEntity(String objectId) {
        this.objectId = objectId;
    }

    public UserEntity(String context,
                      String objectId,
                      String username,
                      String chatId,
                      Date createdAt,
                      String screenName,
                      String email,
                      Integer city,
                      Integer area,
                      String avatarUrl,
                      String about,
                      String contacts,
                      String messages,
                      String parties,
                      String askings,
                      String favParties,
                      String favAskings) {
        this.context = context;
        this.objectId = objectId;
        this.username = username;
        this.chatId = chatId;
        this.createdAt = createdAt;
        this.screenName = screenName;
        this.email = email;
        this.city = city;
        this.area = area;
        this.avatarUrl = avatarUrl;
        this.about = about;
        this.contacts = contacts;
        this.messages = messages;
        this.parties = parties;
        this.askings = askings;
        this.favParties = favParties;
        this.favAskings = favAskings;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getChatId() {
        return chatId;
    }

    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getCity() {
        return city;
    }

    public void setCity(Integer city) {
        this.city = city;
    }

    public Integer getArea() {
        return area;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getAbout() {
        return about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public String getContacts() {
        return contacts;
    }

    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    public String getMessages() {
        return messages;
    }

    public void setMessages(String messages) {
        this.messages = messages;
    }

    public String getParties() {
        return parties;
    }

    public void setParties(String parties) {
        this.parties = parties;
    }

    public String getAskings() {
        return askings;
    }

    public void setAskings(String askings) {
        this.askings = askings;
    }

    public String getFavParties() {
        return favParties;
    }

    public void setFavParties(String favParties) {
        this.favParties = favParties;
    }

    public String getFavAskings() {
        return favAskings;
    }

    public void setFavAskings(String favAskings) {
        this.favAskings = favAskings;
    }
}
