package com.aumum.app.mobile.core.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO_ENTITY.
 */
public class UserInfoEntity extends BaseEntity  {

    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String chatId;
    /** Not-null value. */
    private java.util.Date createdAt;
    private String screenName;
    private String avatarUrl;
    private String city;
    private Integer credit;

    public UserInfoEntity() {
    }

    public UserInfoEntity(String objectId) {
        this.objectId = objectId;
    }

    public UserInfoEntity(String objectId,
                          String chatId,
                          java.util.Date createdAt,
                          String screenName,
                          String avatarUrl,
                          String city,
                          Integer credit) {
        this.objectId = objectId;
        this.chatId = chatId;
        this.createdAt = createdAt;
        this.screenName = screenName;
        this.avatarUrl = avatarUrl;
        this.city = city;
        this.credit = credit;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getChatId() {
        return chatId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getCredit() {
        return credit;
    }

    public void setCredit(Integer credit) {
        this.credit = credit;
    }
}
